import "./globals.css";
import { Toaster } from "@/components/ui/toaster" 

export const metadata = {
  title: "Kasku",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main>{children}</main> 
        <Toaster /> 
      </body>
    </html>
  );
}